version: 2
jobs:
  build:

    docker:
      - image: goldfenix/backframe

    working_directory: /usr/src/app

    branches:
      only:
        - master

    steps:
      - run:
          name: test
          command: npm test
